### ISSUE TITLE
ERROR/Invalid

### ISSUE THREAD

**Issue by Fyrtarn-SNEJ001** [ewanhowell5195/resourcePackConverter#1]
I tried to convert a 1.16 pack to a 1.13 pack and I got this error:

~~ ERROR ~~
Expecting value: line 1 column 1 (char 0)

Also the emissive.properties file was skipped and i figured out that it won't change the pack-format.

**Comment by ewanhowell5195** [comment]
Can you send me a zip of the pack please

**Comment by ewanhowell5195** [comment]
closing as no pack was sent
