### ISSUE TITLE
[BUG] Can't convert 1.17 to 1.16 (nor 1.16.5)

### ISSUE THREAD

**Issue by Juknum** [ewanhowell5195/resourcePackConverter#4]
How to reproduce: 
1. Take a pack (I've used C64x 1.17)
2. Use the latest .exe from this repo
3. Enter 1.17 as base pack
4. Enter 1.16 or 1.16.5 as output
5. See this error:

![image](https://user-images.githubusercontent.com/49886317/112887026-fb627e00-90d2-11eb-8849-fb09442d4073.png)

Additional content: 
My base pack was on my desktop, is it linked?

**Comment by ewanhowell5195** [comment]
1.17 wont be supported until it releases

**Comment by Juknum** [comment]
sad :'(
